version: '3'
services: 
  front:
    container_name: react
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes: 
      - ./frontend:/usr/src/app
    command: ash -c "yarn start"
    ports:
      - '3000:3000'
    tty: true
  api:
    container_name: go-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/go/
    command: ash -c "go run src/main.go"
    tty: true
    ports:
      - 8080:8080
    depends_on: 
      - "db"
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_database
      MYSQL_USER: ucchy
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db: ~