version: '3'
services: 
  front:
    container_name: react
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-front
    volumes: 
      - ./frontend:/usr/src/app
    command: ash -c "yarn start"
    ports:
      - '3000:3000'
    tty: true
  api:
    container_name: go-api
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-api
    volumes:
      - ./backend:/go/src/app
    command: ash -c "go run main.go"
    tty: true
    ports:
      - 8080:8080
    depends_on: 
      - "db"
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ucchy
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - db-volume:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db-volume:
